version: "3.8"

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: bookstore-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: bookstore
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - bookstore-network

  # Backend API
  backend:
    build: .
    container_name: bookstore-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/bookstore?authSource=admin
      JWT_SECRET: ${JWT_SECRET:-your-jwt-secret-change-this-in-production}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-your-refresh-secret-change-this-in-production}
      JWT_EXPIRE: 15m
      JWT_REFRESH_EXPIRE: 7d
      COOKIE_SECRET: ${COOKIE_SECRET:-your-cookie-secret-change-this-in-production}
      CLIENT_URL: http://localhost:3000
      FRONTEND_URL: http://localhost:8080
      BCRYPT_ROUNDS: 12
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
    depends_on:
      - mongodb
    networks:
      - bookstore-network

  # Frontend (optional nginx server for production)
  frontend:
    image: nginx:alpine
    container_name: bookstore-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ../:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - bookstore-network

volumes:
  mongodb_data:
    driver: local

networks:
  bookstore-network:
    driver: bridge
