# Railway Configuration
# This file helps Railway understand how to deploy your backend

[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "npm start"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[runtime]
  nodejs = "18"